[Bitwarden] Mockup for middleware support
gissilabs/charts pull request #7
Opened 2020-09-08 23:10 UTC by Ornias1993

This PR adds a mockup of what middleware support might look like

2020-09-12 19:18 UTC, Ornias1993 commented
@sgissi 
It passed my CI now and it's cleaned up a little :)

2020-09-15 17:08 UTC, sgissi requested changes

2020-09-15 18:12 UTC, Ornias1993 commented on bitwardenrs/values.yaml
> +  # env:
Feel free to send a suggestion so I can easily merge it.

2020-09-15 18:12 UTC, Ornias1993 commented on bitwardenrs/values.yaml
> +  # SIGNUPS_ALLOWED: true
Feel free to send a suggestion so I can easily merge it.

2020-09-15 18:12 UTC, Ornias1993 commented on bitwardenrs/templates/ingressroute.yaml
> +    {{- range .Values.ingressRoute.entrypoints }}
Feel free to send a suggestion so I can easily merge it.

2020-09-15 18:14 UTC, Ornias1993 commented on bitwardenrs/values.yaml
> -  #domain:
If you noticed I ran them past my CI, good form dictates a space after #
Just because it's "easier" doesn't mean it's the way it should be done.

2020-09-24 16:02 UTC, sgissi commented
@Ornias1993 Can you check the patches I have sent? I reverted the space change and updated the rest. I understand they came from YAML lint but suggestions need to take context into consideration. Explanation comments must adhere to the spacing so they are readable. Configuration options is a different thing, likely I will make them explicit instead of a comment section in the future but for now, I will keep the current format without the leading space and with a trailing space.

2020-09-24 16:18 UTC, Ornias1993 commented
- Trailing spaces are "how not to code or comment 101"

- Not using spaces in front of commenting is very non-standard and not something i'm even open to discussing. It's freaking confusing because no-one does.

Sorry you're not going to change my mind on that.

---
About the code:
- code looks fine 👍

2020-09-24 16:27 UTC, sgissi commented
No problem, I was just explaining my rationale, not trying to change your mind. For regular comments we are in agreement (leading space, no trailing). For configuration options, I rather have the way I did. We can agree to disagree on that :)

I'll finish my testing and merge. Thank you very much for the help and effort getting these features in.

2020-09-24 16:32 UTC, merged

2020-09-24 16:37 UTC, Ornias1993 commented
> We can agree to disagree on that :)

Precisely! 👍 

> I'll finish my testing and merge. Thank you very much for the help and effort getting these features in.

No problem, thanks for the quick work on this :)